version = 1

exclude_patterns = ["vendor/**"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/LacazeThomas/nicehash-exporter"]
  dependencies_vendored = true

[[analyzers]]
name = "test-coverage"
enabled = true


